### ISSUE TITLE
Upsert returning uid

### ISSUE THREAD

**Issue by arnodirlam** [liveforeverx/dlex#50]
I'm trying to achieve an upsert, also modifying the node, and always returning the uid. The upsert criteria is just an eq lookup on a field, no logic involved. What would be the best way to achive this?

The [dgraph docs](https://docs.dgraph.io/howto/#upserts) mention two ways to do upserts:
1. Using a transaction - this would naturally cause another request round trip but that's ok
2. Using an upsert block - this doesn't return the uid if the node already existed, at least in Ratel, but I could query for the uid right after the upsert

I tried both approaches with dlex, but feel that the documentation plus looking at the code doesn't give me enough knowledge to achieve this.

Here's what I tried:
```
id = "user1"
statement =
  ~s"""
  upsert {
    query {
      v as var(func: eq(id, "#{id}"))
    }

    mutation {
      set {
        uid(v) <id> "#{id}" .
      }
    }
  }
  """
Dlex.mutate!(conn, statement)
```

grpc gave me a parsing error:
```
while lexing upsert { at line 1 column 0: Unexpected char 'p' when parsing uid keyword
```

Then, I tried it with HTTP, which gave me a different parsing error:
```
at line 1 column 7: Invalid character '{' inside mutation text
```

I also tried using a transaction, but got:
```
StartTs cannot be zero while committing a transaction
```

I'm happy to help with an PR to extend the documentation once this is solved :)

Thanks for your great work! Cheers

**Comment by emhagman** [comment]
Thanks for bringing this to our attention! Quick question first. Have you tried running the query inside of Ratel to confirm it is valid? When you say "tried with HTTP", do you mean through Dlex or directly using some other HTTP client?

I'd like to confirm this is `dlex` specific and not an issue with Dgraph or the query.

**Comment by liveforeverx** [comment]
@arnodirlam Hi! Thank you for reporting the issue.

To use the upsert, you need to do this in this way:

```elixir
id = "user1"
Dlex.mutate!(pid, %{query: ~s|{ v as var(func: eq(id, "#{id}")) }|}, ~s|uid(v) <id> "#{id}" .|, return_json: true)
```

As per grpc protocol query / condition / mutation are different fields in request.

On usage example, I should update the documentation. The documentation for using the upsert are tests right now, see here: https://github.com/liveforeverx/dlex/blob/master/test/dlex_test.exs#L133-L173

But the problem is, that upsert doesn't return the affecting uids, so we need to refer back to dgraph for asking if it is possible to return upsert uids.

**Comment by liveforeverx** [comment]
Fixed in https://github.com/dgraph-io/dgraph/releases/tag/v1.1.1
